spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud
    username: dbadmin
    password: dl123
  jpa:
    hibernate:
      ddl-auto: update
    temp:
      use_jdbc_metadata_defaults: false  
