spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud
    username: dbadmin
    password: dl123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
